import test from "node:test";
import assert from "node:assert/strict";
import http from "node:http";
import {crawlWebsite} from "../lib/audit-crawler";
import {calculateAuditScores} from "../lib/audit-scoring";

async function fixture(){const server=http.createServer((req,res)=>{if(req.url==="/"){res.writeHead(200,{"content-type":"text/html","x-frame-options":"DENY"});res.end(`<!doctype html><html><body><h1>Home</h1><a href="/about">About</a><a href="/missing">Missing</a><img src="x.png"><form><input></form></body></html>`)}else if(req.url==="/about"){res.writeHead(200,{"content-type":"text/html"});res.end(`<!doctype html><html lang="en"><head><title>A properly descriptive about page title for testing</title><meta name="description" content="A sufficiently specific fixture description used to verify deterministic multi-page analysis without any external network dependency."><meta name="viewport" content="width=device-width"><link rel="canonical" href="/about"></head><body><h1>About</h1><a href="mailto:test@example.com">Email</a><button>Book now</button></body></html>`)}else{res.writeHead(404,{"content-type":"text/html"});res.end("missing")}});await new Promise<void>(resolve=>server.listen(0,"127.0.0.1",resolve));const address=server.address();if(!address||typeof address==="string")throw Error("fixture failed");return{server,url:`http://127.0.0.1:${address.port}/`}}
test("controlled fixture crawl is bounded, same-origin, multi-page, and records broken pages",async()=>{const f=await fixture();try{const progress:number[]=[],result=await crawlWebsite(f.url,{pagesRequested:3,validateUrl:async url=>new URL(url),onProgress:current=>{progress.push(current)}});assert.equal(result.pages.length,2);assert.ok(result.pages.every(p=>new URL(p.url).origin===new URL(f.url).origin));assert.ok(result.findings.some(x=>x.category==="broken_links"&&x.severity==="high"));assert.ok(result.measurements.some(x=>x.metricKey==="title"));assert.ok(progress.length>=2)}finally{f.server.close()}});
test("page limit is enforced",async()=>{await assert.rejects(()=>crawlWebsite("https://example.com",{pagesRequested:11,validateUrl:async u=>new URL(u)}),/INVALID_PAGE_LIMIT/)});
test("transparent scoring applies severity deductions and leaves unavailable categories unscored",()=>{const findings=[{category:"seo" as const,severity:"critical" as const,title:"x",description:"x",evidence:"x",impact:"x",recommendation:"x",pageUrl:null,provenance:"measured" as const,clientVisible:true,selectedForProposal:true}],scores=calculateAuditScores(findings,{seo:true});assert.equal(scores.categories.seo.score,65);assert.equal(scores.categories.mobile.score,null);assert.equal(scores.overall,65);assert.equal(scores.inputs.severityDeductions.critical,35)});
