import test from "node:test";
import assert from "node:assert/strict";
import { bulkInsertMeasurements, consumeAuditRateLimit, createAuditRetry, createFounderFinding, createQueuedAudit, listFindings, markAuditCancelled, markAuditCompleted, markAuditFailed, persistAuditProgress, reorderFindings, setAuditArchived, startQueuedAudit, updateFinding } from "../lib/audits";

const now=()=>new Date().toISOString();
function row(overrides:Record<string,unknown>={}){return {id:"a1",lead_id:"l1",status:"queued",target_url:"https://example.com",final_url:null,started_at:now(),completed_at:null,created_at:now(),updated_at:now(),summary:"",findings:[],metrics:{},pages_checked:0,links_checked:0,internal_notes:"",error_message:null,normalized_domain:"example.com",failed_at:null,cancelled_at:null,archived_at:null,failure_code:null,failure_message:null,retry_count:0,retried_from_audit_id:null,pages_requested:3,pages_scanned:0,progress_current:0,progress_total:3,progress_message:"Queued",report_version:2,...overrides}}
type Result={rows:Record<string,unknown>[];rowCount?:number};
type Query={query:(sql:string,values?:unknown[])=>Promise<Result>};

test("queued creation stores normalized domain, requested pages, and report version",async()=>{let args:unknown[]=[];const q:Query={query:async(_s,v=[])=>{args=v;return{rows:[row()]}}};const a=await createQueuedAudit({leadId:"l1",targetUrl:"https://Example.com/a",pagesRequested:3,reportVersion:2},q);assert.equal(a.status,"queued");assert.deepEqual(args.slice(2,6),["https://Example.com/a","example.com",3,2])});

test("valid lifecycle persists progress and completes; invalid transition is rejected",async()=>{let state="queued";const q:Query={query:async(sql,v=[])=>{if(sql.includes("set status='running'")){if(state!=="queued")return{rows:[]};state="running"}else if(sql.includes("progress_current=$1")){assert.equal(state,"running");return{rows:[row({status:state,progress_current:v[0],progress_total:v[1],progress_message:v[2],pages_scanned:v[3]})]}}else if(sql.includes("set status='completed'")){if(state!=="running")return{rows:[]};state="completed"}return{rows:[row({status:state,completed_at:state==="completed"?now():null})]}}};await startQueuedAudit("a1",q);const progress=await persistAuditProgress("a1",{progressCurrent:2,progressTotal:3,progressMessage:"Two pages",pagesScanned:2},q);assert.equal(progress.pagesScanned,2);assert.equal((await markAuditCompleted("a1",q)).status,"completed");await assert.rejects(()=>startQueuedAudit("a1",q),/INVALID_AUDIT_TRANSITION/)});

test("failure, cancellation, archive and retry lineage persist",async()=>{const failedQ:Query={query:async(_s,v=[])=>({rows:[row({status:"failed",failed_at:now(),failure_code:v[0],failure_message:v[1]})]})};const failed=await markAuditFailed("a1","FETCH_TIMEOUT","Safe message",failedQ);assert.equal(failed.failureCode,"FETCH_TIMEOUT");assert.equal(failed.failureMessage,"Safe message");const cancelQ:Query={query:async()=>({rows:[row({status:"cancelled",cancelled_at:now()})]})};assert.equal((await markAuditCancelled("a1",cancelQ)).status,"cancelled");const archiveQ:Query={query:async()=>({rows:[row({archived_at:now()})]})};assert.ok((await setAuditArchived("a1",true,archiveQ))?.archivedAt);
 let calls=0;const retryQ:Query={query:async(sql)=>{calls++;if(sql.startsWith("select"))return{rows:[row({status:"failed",retry_count:2})]};return{rows:[row({id:"a2",retried_from_audit_id:"a1",retry_count:3})]}}};const retry=await createAuditRetry("a1",retryQ);assert.equal(calls,2);assert.equal(retry.retriedFromAuditId,"a1");assert.equal(retry.retryCount,3)});

test("raw measurements are inserted independently of editable findings",async()=>{let measurementValue:unknown;const q:Query={query:async(sql,v=[])=>{if(sql.startsWith("insert into crm_audit_measurements")){measurementValue=v[5];return{rows:[{id:"m1",audit_id:"a1",page_url:v[2],category:v[3],metric_key:v[4],value:JSON.parse(v[5] as string),available:v[6],captured_at:now()}]}}if(sql.startsWith("update crm_audit_findings"))return{rows:[findingRow({recommendation:v[0]})]};throw Error(sql)}};await bulkInsertMeasurements("a1",[{pageUrl:"https://example.com",category:"seo",metricKey:"title",value:{present:false},available:true}],q);await updateFinding("f1",{recommendation:"Add a title"},q);assert.equal(measurementValue,JSON.stringify({present:false}))});

function findingRow(o:Record<string,unknown>={}){return{id:"f1",audit_id:"a1",category:"seo",severity:"high",title:"Missing title",description:"Title absent",evidence:"No title",impact:"Search",recommendation:"Add title",page_url:"https://example.com",provenance:"founder",client_visible:true,selected_for_proposal:false,sort_order:0,created_at:now(),updated_at:now(),...o}}
test("founder findings and editable visibility, proposal selection, severity filters persist",async()=>{let lastSql="",lastValues:unknown[]=[];const q:Query={query:async(sql,v=[])=>{lastSql=sql;lastValues=v;if(sql.startsWith("insert"))return{rows:[findingRow()]};if(sql.startsWith("update"))return{rows:[findingRow({client_visible:v[0],selected_for_proposal:v[1]})]};return{rows:[findingRow()]}}};const base={category:"seo" as const,severity:"high" as const,title:"Missing title",description:"Absent",evidence:"HTML",impact:"Discovery",recommendation:"Add it",pageUrl:null,clientVisible:true,selectedForProposal:false};assert.equal((await createFounderFinding("a1",base,q)).provenance,"founder");const edited=await updateFinding("f1",{clientVisible:false,selectedForProposal:true},q);assert.equal(edited?.clientVisible,false);assert.equal(edited?.selectedForProposal,true);await listFindings("a1",{severity:"high",clientVisible:true},q);assert.match(lastSql,/severity=\$2.*client_visible=\$3/);assert.deepEqual(lastValues,["a1","high",true])});

test("finding reorder is persisted transactionally",async()=>{const calls:string[]=[];const client={query:async(sql:string,v?:unknown[])=>{calls.push(v?`${sql}:${v.join(",")}`:sql);return{rows:[],rowCount:sql.startsWith("update")?1:null}}};await reorderFindings("a1",["f2","f1"],client as never);assert.equal(calls[0],"begin");assert.match(calls[1],/f2,a1$/);assert.match(calls[2],/f1,a1$/);assert.equal(calls[3],"commit")});

test("shared limiter enforces, resets, and atomically caps concurrent consumption",async()=>{const counts=new Map<string,number>();const q:Query={query:async(_sql,v=[])=>{await new Promise(r=>setTimeout(r,Math.random()*3));const key=v[0] as string,limit=v[2] as number,current=counts.get(key)??0;if(current>=limit)return{rows:[]};counts.set(key,current+1);return{rows:[{attempts:current+1,window_started_at:v[1]}]}}};const at=new Date("2026-01-01T00:00:00Z"),results=await Promise.all(Array.from({length:20},()=>consumeAuditRateLimit({actorKey:"session",limit:5,windowSeconds:60,now:at},q)));assert.equal(results.filter(x=>x.allowed).length,5);assert.equal((await consumeAuditRateLimit({actorKey:"session",limit:5,windowSeconds:60,now:new Date("2026-01-01T00:01:00Z")},q)).allowed,true)});
