import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { CTABand } from "@/components/studio";
import StudioFooter from "@/components/studio/StudioFooter";
import StudioNav from "@/components/studio/StudioNav";

export const metadata: Metadata = { title: "About the Founder-Led Studio", description: "Meet Blake Taylor and learn why Koinophobia Labs operates as a focused founder-led studio for useful websites, workflows, and software.", alternates: { canonical: "/about" }, openGraph: { url: "/about" } };
export default function AboutPage() { return <div className="studio-site"><StudioNav /><main><header className="studio-page-hero"><div className="studio-container"><p className="studio-eyebrow">About Koinophobia Labs</p><h1>A focused studio, built around direct responsibility.</h1><p className="studio-page-hero__lede">Koinophobia Labs combines business diagnosis, product thinking, interface design, AI workflows, implementation, and delivery without passing the client between departments.</p></div></header><section className="studio-section studio-section--compact"><div className="studio-container studio-founder-grid"><div className="studio-founder-photo"><Image src="/blake-portrait.jpg" alt="Blake Taylor, founder of Koinophobia Labs" fill sizes="(max-width: 760px) 100vw, 420px" priority /></div><div className="studio-founder-copy"><p className="studio-eyebrow">Blake Taylor, founder</p><h2>You work with the builder.</h2><p>Blake scopes the problem, designs the solution, builds the system, runs the critical checks, and leads the handoff. That direct line is the operating model, not a temporary substitute for an agency structure.</p><p>His background includes high-volume customer operations at DraftKings, a B.A. in Global Management from Earlham College, and sustained product work across Career Forge, Trendi, and You Know Ball.</p><p>Internal products demonstrate product and engineering capability. They are not used as substitutes for external client proof, and the studio’s public business-work inventory is labeled conservatively.</p><Link className="studio-text-link" href="/resume">Review Blake’s operator background <ArrowRight size={16} aria-hidden="true" /></Link></div></div></section><CTABand /></main><StudioFooter /></div>; }
