import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title: "Way In Purchase and Use Information", description: "What Free, Resume Toolkit, and the 30-Day Career Pass include. Apple purchase confirmation, restoration, and support.", alternates: { canonical: "/way-in/terms" } };
export default function TermsPage() {
  return <main className="legal-page"><Link className="legal-back" href="/way-in">← Way In</Link><h1>Way In purchase and use information</h1><p className="legal-note">Updated October 5, 2026 · Native iPhone and iPad app</p>
    <section><h2>App license</h2><p>The app is licensed through Apple under Apple’s <a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/">Standard Licensed Application End User License Agreement</a>. This page explains the app’s offer and purchase behavior; it does not replace that agreement or your statutory consumer rights.</p></section>
    <section><h2>Free access</h2><p>Free access lets you capture experience, start or import résumés, save jobs, and check job fit. Full review, editing, and export of saved résumés require an eligible purchase.</p></section>
    <section><h2>Resume Toolkit</h2><p>Resume Toolkit is a non-consumable, one-time purchase: currently US $9.99. It unlocks full saved-résumé review, editing, and PDF/DOCX export without a time limit. It does not include job-specific tailoring, application drafts, interview preparation, or career planning.</p></section>
    <section><h2>30-Day Career Pass</h2><p>Career Pass is a non-renewing purchase: currently US $29.99 for 30 days beginning at purchase. It includes résumé access, job-specific tailoring, application drafts, interview preparation, and career planning during that period. It expires automatically and does not charge again unless you make another purchase. There is no recurring subscription to cancel. Toolkit is not required to use the pass; permanent Toolkit access is a separate purchase.</p><p>When a pass ends, saved work remains on the device and exported files remain yours. Paid features lock unless you have another eligible entitlement. A separately purchased Toolkit continues to provide its résumé access.</p></section>
    <section><h2>Price, confirmation, restore, and refunds</h2><p>Apple shows the applicable local price before you confirm a purchase and charges your App Store account. Use Profile → Settings → Access → Restore App Store purchases with the Apple Account that purchased. Restoring a pass does not restart its 30 days. If you have a payment or refund request, use <a href="https://reportaproblem.apple.com/">Apple’s purchase support</a>. Refund eligibility is determined by Apple and applicable law.</p><p>Older Career Forge web purchases used a separate payment and access system. They do not automatically unlock the current iOS release. Contact support with the receipt reference if you need help; do not send payment-card details.</p></section>
    <section><h2>Your applications</h2><p>Way In helps you prepare and organize. It is not an employer, recruiter, or guarantee of an interview, offer, salary, or applicant-tracking-system result. Review the facts, wording, dates, files, and destination before using any material. You submit through the employer’s website and record the result yourself. Your content remains yours.</p></section>
    <section><h2>Privacy and help</h2><p>Read the <Link href="/way-in/privacy">Way In Privacy Policy</Link>. For help with access or saved work, see <Link href="/way-in/support">Support</Link> or email <a href="mailto:koinophobia999@gmail.com">koinophobia999@gmail.com</a>.</p></section>
  </main>;
}
