import {PDFDocument,StandardFonts,rgb,type PDFFont,type PDFPage} from "pdf-lib";
import type {LeadRecord} from "@/lib/acquisition/leads";
import type {AuditRecord,NormalizedFindingRecord} from "@/lib/audits";

export async function renderAuditPdf(a:AuditRecord,lead:LeadRecord,normalized?:NormalizedFindingRecord[]){
 const findings=normalized?.filter(f=>f.clientVisible)??a.findings,scores=a.scores as{overall?:number|null;categories?:Record<string,{score:number|null;available:boolean}>}|undefined,doc=await PDFDocument.create(),regular=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold);let page:PDFPage,y=0;
 const add=()=>{page=doc.addPage([612,792]);page.drawRectangle({x:0,y:0,width:612,height:792,color:rgb(1,1,1)});y=742;page.drawText("KOINOPHOBIA LABS",{x:48,y,size:11,font:bold,color:rgb(.02,.55,.62)});page.drawText(`Website audit ${a.id.slice(0,8).toUpperCase()} v${a.reportVersion??1}`,{x:375,y,size:9,font:regular,color:rgb(.35,.39,.43)});y-=35};
 const wrap=(s:string,font:PDFFont,size:number,w:number)=>{const lines:string[]=[],words=s.replace(/\s+/g," ").trim().split(" ");let line="";for(const word of words){const n=line?`${line} ${word}`:word;if(font.widthOfTextAtSize(n,size)>w){if(line)lines.push(line);line=word}else line=n}if(line)lines.push(line);return lines},ensure=(h:number)=>{if(y-h<58)add()},height=(s:string,size=9,b=false)=>wrap(s,b?bold:regular,size,516).length*(size+4)+3,text=(s:string,size=10,b=false,indent=0,color=rgb(.08,.1,.13))=>{const f=b?bold:regular,lines=wrap(s,f,size,516-indent);ensure(lines.length*(size+4)+5);for(const line of lines){page.drawText(line,{x:48+indent,y,size,font:f,color});y-=size+4}y-=3},head=(s:string)=>{ensure(30);y-=8;text(s.toUpperCase(),10,true)};add();
 text(`Website Audit: ${lead.businessName}`,24,true);text(a.finalUrl||a.targetUrl,10);text(`Completed ${a.completedAt?new Date(a.completedAt).toLocaleDateString("en-US"):"in progress"} | ${a.pagesChecked} pages | ${a.linksChecked} internal links discovered`,9);head("Executive summary");text(a.summary);
 if(scores){head("Transparent scores");text(`Overall: ${scores.overall??"Unavailable"}`,15,true);for(const [name,s]of Object.entries(scores.categories??{}))text(`${name.replaceAll("_"," ")}: ${s.available?s.score:"Unavailable"}`,9);text("Available categories begin at 100 and use documented severity-weighted deductions. Unavailable checks are not treated as passes.",8)}
 head("Priority findings");for(const f of findings){const description="description"in f?f.description:"",impact="impact"in f?f.impact:"",needed=height(`${f.severity} / ${f.category} - ${f.title}`,10,true)+height(description)+height(`Evidence: ${f.evidence}`)+height(`Impact: ${impact}`)+height(`Recommendation: ${f.recommendation}`)+20;ensure(Math.min(needed,650));text(`${f.severity.toUpperCase()} / ${f.category.toUpperCase().replaceAll("_"," ")} - ${f.title}`,10,true,0,f.severity==="critical"||f.severity==="high"?rgb(.66,.12,.12):f.severity==="positive"?rgb(.05,.43,.26):rgb(.08,.1,.13));if(description)text(description,9);text(`Evidence: ${f.evidence}`,9);if(impact)text(`Impact: ${impact}`,9);text(`Recommendation: ${f.recommendation}`,9);y-=5}
 head("Limitations");text("Accessibility results are an automated screening, not certification. Security results are a surface-level review, not a penetration test. Conversion findings use structured heuristics and founder judgment. Browser rendering, Core Web Vitals, visual responsiveness, color contrast, and full WCAG conformance require separate testing.",9);
 for(let i=0;i<doc.getPageCount();i++){const p=doc.getPage(i);p.drawLine({start:{x:48,y:38},end:{x:564,y:38},thickness:.5,color:rgb(.8,.82,.84)});p.drawText(`Koinophobia Labs | koinophobialabs.com | ${i+1} of ${doc.getPageCount()}`,{x:48,y:24,size:8,font:regular,color:rgb(.4,.43,.46)})}doc.setTitle(`Website Audit - ${lead.businessName}`);doc.setAuthor("Koinophobia Labs");return Buffer.from(await doc.save());
}
