import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title: "Way In Support", description: "Help with purchases, restoration, résumé access, imports, exports, and private career data.", alternates: { canonical: "/way-in/support" } };
export default function SupportPage() {
  return <main className="legal-page"><Link className="legal-back" href="/way-in">← Way In</Link><h1>Way In support</h1><p>Need help getting to your next step? Email <a href="mailto:koinophobia999@gmail.com?subject=Way%20In%20support">koinophobia999@gmail.com</a>. Include your app version, device, what you tried, and what happened. A redacted screenshot helps. Please leave out private résumé details, passwords, and payment-card numbers.</p>
    <section><h2>I paid, but my résumé is still locked</h2><ol><li>Use the same Apple Account that made the purchase.</li><li>Open Profile → Settings → Access → Restore App Store purchases.</li><li>Return to your saved résumé. You do not need to create it again.</li><li>If access still doesn’t appear, email support with the Apple receipt reference and app version.</li></ol><p>Career Pass lasts 30 days from purchase. Restore does not restart an expired pass. Resume Toolkit does not expire. A pending purchase unlocks only after Apple approves it.</p></section>
    <section><h2>The purchase options won’t load</h2><p>Check your connection and App Store account, then reopen the Access screen. No payment is made until you confirm in Apple’s purchase sheet. Your saved career work stays in the app.</p></section>
    <section><h2>I want to cancel or request a refund</h2><p>Neither Way In purchase auto-renews, so there is no recurring subscription to cancel. For purchase or refund requests, use <a href="https://reportaproblem.apple.com/">Apple’s purchase support</a>.</p></section>
    <section><h2>A résumé or job link won’t import</h2><p>Try pasting the résumé text or job description. Some files are scanned images and some websites prevent page reading. Review imported names, dates, employers, and wording before using them. A saved link is not confirmation that a job is still open.</p></section>
    <section><h2>How do I submit an application?</h2><p>Prepare and review your materials, export the file, then open the employer’s site. Attach and submit it there. Return to Way In and record whether you submitted, saved a draft, or need to check. Way In does not apply on your behalf.</p></section>
    <section><h2>How do I back up or delete my data?</h2><p>Profile → Settings contains Backup and restore, optional iCloud continuity, and Data deletion. Backups containing saved résumés require résumé access. Delete an iCloud copy separately if you enabled it. Exported files remain wherever you saved them. Support cannot retrieve an unsynced local workspace.</p></section>
    <section><h2>Getting started</h2><p>Bring one real experience or an existing résumé, then add a job posting. Check experience fit before deciding whether you need a paid feature. <Link href="/way-in#pricing">Compare the two purchase options</Link>.</p><p><Link href="/way-in/privacy">Privacy</Link> · <Link href="/way-in/terms">Purchase and use information</Link></p></section>
  </main>;
}
