import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Preaching to the Choir Privacy Policy",
  description: "How Preaching to the Choir version 1.0 handles prayers, recordings, permissions, exports, and purchases.",
  alternates: { canonical: "/preaching-to-the-choir/privacy" },
};

export default function PrivacyPage() {
  return <main className="legal-page">
    <Link className="legal-back" href="/preaching-to-the-choir/support">← Preaching to the Choir support</Link>
    <p className="kicker kicker-orange">Preaching to the Choir</p>
    <h1>Privacy Policy</h1>
    <p className="legal-note">Effective September 16, 2026 · App Store version 1.0</p>
    <section><h2>Your record belongs on your device</h2><p>Preaching to the Choir is a private prayer journal from Koinophobia Labs. The app requires no account. Prayer text, recordings, transcripts, reflection notes, names, labels, threads, dates, and settings are stored in the app’s local container. Koinophobia Labs does not receive this content. This version does not sync your record to iCloud.</p></section>
    <section><h2>Recording, speech, and contacts</h2><p>The app asks for microphone access when you choose to record. Audio is saved locally. Optional transcription uses Apple’s on-device speech recognition; it does not upload your recordings for transcription. Apple may download speech assets needed for supported languages. When local recognition is unavailable, the app preserves the recording and offers the relevant recovery or language choices.</p><p>If you enable contact-name hints, the app requests contact access and uses permitted contact names locally as transcription hints. It does not upload your contact list or save that list with your prayers. Names you speak or write can remain part of your own record.</p><p>Keyboard dictation is Apple’s separate service and follows your Apple dictation settings. Third-party keyboard extensions are excluded from this app.</p></section>
    <section><h2>Local processing, identifiers, and diagnostics</h2><p>Search, name recognition, shared-word suggestions, and reflection organization run on your device. There is no external AI API, advertising SDK, tracking SDK, or third-party analytics SDK. Your prayers are not sent for model training. The App Store version does not collect analytics or send app-operated crash reports. A random installation identifier is used inside the local database and is not transmitted to Koinophobia Labs.</p><p>Apple may provide diagnostics or App Store information under your device and Apple Account settings. These are Apple’s services, separate from an app-operated reporting system.</p></section>
    <section><h2>Permissions and device protection</h2><p>Microphone, speech, optional contact hints, and optional local notifications serve the features described above. Notifications contain generic prompts rather than prayer text. The optional app lock uses Apple’s device authentication; the app does not receive or store biometric templates or your device passcode.</p><p>Files use iOS data protection. Database files become available after the device has first been unlocked after restart. Recording protection permits an already-open recording to finish while the device locks. The app lock provides an additional reading barrier. Screenshots and files you choose to share are outside that barrier.</p></section>
    <section><h2>Apple purchases and other services</h2><p>Optional Keeper purchases use Apple StoreKit. Apple processes payment and account information under its privacy policy. The app reads verified purchase status locally to provide membership features; Koinophobia Labs does not operate a purchase-account database or receive payment-card details through the app.</p><p>Apple also provides operating-system speech assets, device backup, authentication, and permission services. The app includes GRDB for its local database; that library is not an external data processor. Crisis-resource actions hand off to your device’s calling or messaging app only when you choose an action.</p></section>
    <section><h2>Retention and deletion</h2><p>Your record remains on your device until you remove it. Deleting a prayer moves it to Recently Deleted for 30 days, after which the app removes it through its local cleanup. You can restore it during that period or choose Delete now. Settings → Erase everything removes the local record, recordings, derived data, settings, and app-managed export files. No app account exists to delete.</p><p>Deletion does not remove copies you exported or shared, or existing device backups. Manage those copies with their respective destinations. Removing the app removes its local container but does not cancel an Apple subscription or erase external backups.</p></section>
    <section><h2>Exports and backups</h2><p>Export and sharing happen at your request, to the destination you select. Ordinary exports, PDFs, and recordings are readable by their recipients. Full-record exports can optionally be encrypted with a passphrase using Apple-provided cryptography. Koinophobia Labs cannot recover your passphrase.</p><p>Because live sync is unavailable, this version permits the record to be included in device backups. Apple’s iCloud Backup and your computer-backup settings determine whether those copies leave the device and how they are protected. A backup or export can contain your prayer text and audio.</p></section>
    <section><h2>This website and support</h2><p>These pages are hosted by Vercel. Hosting infrastructure processes technical request information, such as IP address and browser details, to deliver them. The website also uses Vercel Web Analytics for website usage. This is separate from the journal app and does not receive its contents. See the <Link href="/privacy">website privacy policy</Link>.</p><p>If you email support, we receive your email address and whatever you include so we can respond. Gmail processes those messages. Avoid sending private prayers, recordings, or passphrases. You may request deletion of support correspondence by email; existing provider backups or records required for legal obligations may remain.</p></section>
    <section><h2>Children</h2><p>The app is a general-audience journal and is not directed specifically to children. It does not collect journal content or analytics from its users. If a child sends personal information to support, a parent or guardian may contact us to request deletion.</p></section>
    <section><h2>Questions and changes</h2><p>Contact <a href="mailto:koinophobia999@gmail.com">koinophobia999@gmail.com</a> for privacy questions or support-data requests. We will update this policy if the app’s practices change; the effective date identifies this version.</p><p>Preaching to the Choir · Koinophobia Labs</p></section>
  </main>;
}
