import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title: "Way In Privacy Policy", description: "How the Way In iOS app handles your career data, purchases, optional iCloud continuity, and support.", alternates: { canonical: "/way-in/privacy" } };
export default function PrivacyPage() {
  return <main className="legal-page">
    <Link className="legal-back" href="/way-in">← Way In</Link><h1>Way In Privacy Policy</h1><p className="legal-note">Effective October 5, 2026 · Native iPhone and iPad app</p>
    <section><h2>Your career data</h2><p>Way In is made by Koinophobia Labs. Résumés, profile details, job postings, application records, interview practice, and notes are stored in the app’s workspace on your device by default. The app does not send your résumé or career text to a cloud AI service. Career analysis and document preparation run on the device. On supported devices, Apple’s on-device model may help order job requirements.</p><p>No account is required. Some versions offer optional Sign in with Apple and keep an Apple account identifier on the device. The current public release has no configured account server or automatic web-purchase reconciliation service. Signing in does not itself upload or back up your career workspace.</p></section>
    <section><h2>What leaves the device when you choose</h2><p>Opening or reading a saved job link connects to that website, which receives normal network request information. The app does not submit job applications for you. Export, Share, and Files actions create or send the material you select to the destination you choose. PDF, DOCX, and JSON backup files can contain personal career information; manage those copies carefully.</p><p>Optional iCloud continuity is off by default. If enabled, it stores a private workspace file in your iCloud Drive under your Apple Account. You can disable sync or delete that cloud copy in Settings → iCloud continuity. Turning sync off does not delete existing copies. Uploading a workspace containing saved résumé content requires résumé access.</p></section>
    <section><h2>Purchases</h2><p>Apple handles App Store payment details and purchase records. Way In reads verified StoreKit transactions to decide which features are available. Koinophobia Labs does not receive your full card details. Restoring a purchase contacts Apple. A restore does not extend an expired 30-Day Career Pass.</p></section>
    <section><h2>Diagnostics and optional research</h2><p>Way In writes content-free product event names to the device’s system log. This event interface accepts no career text or user identifiers, and the app has no automatic analytics upload. Apple may process App Store or operating-system diagnostics according to your Apple settings and Apple’s policies.</p><p>The optional product proof program starts only after you join it in Settings. It records milestone names, dates, active days, and aggregate application outcomes locally. An exported report includes a random participant code, app/build version, device family, timings, and counts. It excludes résumé, job, company, contact, transcript, note, and account text. Nothing is uploaded automatically; a report leaves the device only when you share it. You can stop and delete the measurements in Settings.</p></section>
    <section><h2>Deletion and recovery</h2><p>Profile → Settings → Data deletion removes the local career workspace and signs you out after confirmation. iCloud copies and previously exported files are separate and must be removed separately. Support cannot recover an unsynced local workspace. Removing data does not cancel, refund, or erase your App Store purchase history. Use the backup tools before deleting work you need to keep.</p></section>
    <section><h2>This website and support</h2><p>This website uses Vercel hosting and Web Analytics to measure visits and outbound clicks. Website activity is separate from your app workspace; see the <Link href="/privacy">website privacy policy</Link>. If you email support, we receive your address and the information you include, through Gmail, to respond. Avoid sending private résumés unless needed for your request. You can request deletion of support correspondence by email; provider backups or records required by law may remain.</p></section>
    <section><h2>Contact and changes</h2><p>For privacy questions, contact <a href="mailto:koinophobia999@gmail.com">koinophobia999@gmail.com</a>. We update this page when the app’s practices change. This policy describes the native Way In app; the separately operated legacy Career Forge web app has its own policy.</p><Link href="/way-in/support">Get help with Way In</Link></section>
  </main>;
}
